name: dating_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # visual
  flutter_native_splash: ^2.2.9
  intl_phone_field: ^3.1.0
  font_awesome_flutter: ^10.2.1
  pin_code_fields: ^7.4.0
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1
  dots_indicator: ^2.0.0
  flutter_switch: ^0.3.2

  # firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.3.0
  cloud_firestore: ^4.4.5

  #utils
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: 5.0.1
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  jiffy: ^5.0.0
  dropdown_button2: ^1.9.1
  geolocator: ^9.0.2
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  geocoding: ^2.0.5
  flutter_local_notifications: ^13.0.0
  ntp: ^2.0.0

  agora_uikit: ^1.1.1
  agora_rtc_engine: ^6.1.0
  permission_handler: ^10.2.0
  audioplayers: ^2.0.0
  quiver: ^3.2.1
  dio: ^4.0.6
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

